FROM golang:1.8.1-alpine
LABEL maintaner="Stegen Smith <matthsmi@adobe.com>

RUN mkdir /root/butler
COPY ./files/doit.sh /doit.sh
COPY ./files/build_test.sh /root/build.sh
COPY butler.go /root/butler/butler.go
COPY config.go /root/butler/config.go
COPY promfuncs.go /root/butler/promfuncs.go
COPY butler_test.go /root/butler/butler_test.go
COPY ./vendor /root/butler/vendor

RUN apk update && apk add bash git

CMD ["/doit.sh"]
