FROM golang:1.8.1-alpine
LABEL maintaner="Stegen Smith <matthsmi@adobe.com>"

ARG VERSION=$VERSION
ENV VERSION=$VERSION

### required to build
RUN mkdir -p /root/butler/stats /root/butler/config /root/butler/config/methods /root/butler/config/reloaders /root/butler/environment /root/butler/alog
COPY ./files/build.sh /root/build.sh
COPY butler.go /root/butler/butler.go
COPY ./config/*.go /root/butler/config/
COPY ./config/methods/*.go /root/butler/config/methods/
COPY ./config/reloaders/*.go /root/butler/config/reloaders/
COPY ./stats/*.go /root/butler/stats/
COPY ./environment/*.go /root/butler/environment
COPY ./alog/*.go /root/butler/alog
COPY ./vendor /root/butler/vendor
### required to build

RUN apk update && apk add bash && apk add ca-certificates

RUN /root/build.sh
