FROM golang:1.8.1-alpine
LABEL maintaner="Stegen Smith <matthsmi@adobe.com>

RUN mkdir -p /root/butler/stats /root/butler/config
COPY ./files/build.sh /root/build.sh
COPY butler.go /root/butler/butler.go
COPY ./config/*.go /root/butler/config/
COPY ./stats/*.go /root/butler/stats/
COPY ./vendor /root/butler/vendor

RUN apk update && apk add bash

RUN /root/build.sh
